#include "GUI/Widget.hpp"
#include "GUI/Canvas.hpp"
#include "GUI/Label.hpp"
#include "GUI/Button.hpp"
#include "GUI/TextField.hpp"
#include "GUI/Box.hpp"
#include "GUI/HistoryGraph.hpp"
#include "GUI/GeometryGraph.hpp"